version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskmanager-api
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Data Source=/data/tasks.db
      # Configure uma ou múltiplas origens
      FrontendOrigins: ${FrontendOrigins:-https://teste-olhar180-frontend.onrender.com}
      # JWT (ajuste conforme necessário)
      Jwt__Issuer: TaskManager
      Jwt__Audience: TaskManager
      Jwt__Secret: ${Jwt__Secret:-b6f9d3c2a1e04f8bb3c76a5d9e2f1c0a7b8d6e5f4a3b2c1d0e9f8a7b6c5d4e3f}
    volumes:
      - api_data:/data
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  api_data:
    name: taskmanager_api_data