version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskmanager-api
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Data Source=/data/tasks.db
      # Configure uma ou múltiplas origens
      FrontendOrigins: ${FrontendOrigins:-http://localhost:5173}
      # JWT (ajuste conforme necessário)
      Jwt__Issuer: TaskManager
      Jwt__Audience: TaskManager
      Jwt__SecretKey: ${Jwt__SecretKey:-supersecretkey123}
    volumes:
      - api_data:/data
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  api_data:
    name: taskmanager_api_data